language: java
jdk:
- openjdk7
branches:
  only:
  - master
  - develop
  - /^feature\/.*$/
  - /^hotfix\/.*$/
  - /^release\/.*$/
cache:
  directories:
  - $HOME/.m2

before_script:
  - mvn clean
  - mvn checkstyle:check
  - mvn cobertura:check
  - mvn pmd:check
  - mvn pmd:cpd-check
script:
  - mvn install
after_success:
  - mvn clean cobertura:cobertura coveralls:report